test: proxy tests
odpf/shield pull request #196
Opened 2023-01-08 17:31 UTC by ishanarya0

2023-01-30 15:48 UTC, ravisuhag commented
@krtkvrm @ishanarya0 is this PR valid after 0.5 merge?

2023-01-30 15:50 UTC, krtkvrm commented
we will continuing this in v0.5.1

2023-02-02 06:29 UTC, krtkvrm requested changes

2023-02-02 06:29 UTC, krtkvrm commented on .github/workflows/test.yml
> +        run: make e2e-smoke-test
add line at end

2023-02-02 06:29 UTC, krtkvrm commented on test/e2e_test/smoke/proxy_test.go
> +	s.Run("1. should be able to proxy to an echo server", func() {
can remove numbers

2023-02-02 10:26 UTC, merged